---
- name: Download Prometheus
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v2.50.1/prometheus-2.50.1.linux-amd64.tar.gz"
    dest: /opt/
    remote_src: yes
    creates: /opt/prometheus-2.50.1.linux-amd64

- name: Create symbolic link for Prometheus
  ansible.builtin.file:
    src: /opt/prometheus-2.50.1.linux-amd64
    dest: /opt/prometheus
    state: link

- name: Copy Prometheus configuration template
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /opt/prometheus/prometheus.yml
    owner: root
    group: root
    mode: '0644'

- name: Create Prometheus systemd service file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      ExecStart=/opt/prometheus/prometheus --config.file=/opt/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus
      Restart=always

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: '0644'

- name: Reload systemd and start Prometheus
  ansible.builtin.systemd:
    name: prometheus
    daemon_reload: yes
    state: started
    enabled: yes
